% Abort left over jobs.
MPI_Abort;
pause(2.0);


% Delete left over MPI directory
MatMPI_Delete_all;
pause(2.0);

[status, result] = system('hostname');
hostname_str = mat2str(result);

if size(strfind(hostname_str, 'Celsius'),1) > 0
    % Define machines, empty means run locally.
    machines = {};
    eval( MPI_Run('LHDMPrimGeneratorMPI',  7, machines) );

elseif size(strfind(hostname_str, 'phoenix'),1) > 0
    % Define machines for cluster
    machines = {...
        'compute-0-0' ...
        'compute-0-1' ...
        'compute-0-2' ...
        'compute-0-3' ...
        'compute-0-4' ...
        'compute-0-5' ...
        'compute-0-6' ...
        'compute-0-7' ...
        'compute-0-8' ...
        'compute-0-9' ...
        'compute-0-10' ...
        'compute-0-11' ...
        'compute-0-12' ...
        'compute-0-13' ...
        'compute-0-14' ...
        'compute-0-15' ...
        'compute-0-16' ...
        'compute-0-17' ...
        'compute-0-18' ...
        'compute-0-19' ...
        'compute-0-20' ...
        'compute-0-21' ...
        'compute-0-22' ...
        'compute-0-23' ...
        'compute-0-24' ...
        'compute-0-25' ...
        'compute-1-0' ...
        'compute-1-1' ...
        'compute-1-2' ...
        'compute-1-3' ...
        'compute-1-4' ...
        'compute-1-5' ...
        'compute-1-6' ...
        'compute-1-7' ...
        'compute-1-8' ...
        'compute-1-9' ...
        'compute-1-10' ...
        'compute-1-11' ...
        'compute-1-12' ...
        'compute-1-13' ...
        'compute-1-14' ...
        'compute-1-15' ...
        'compute-1-16' ...
        'compute-1-17' ...
        'compute-1-18' ...
        'compute-1-19' ...
        'compute-1-20' ...
        'compute-1-21' ...
        'compute-1-22' ...
        'compute-1-24' ...
        'compute-1-25' ...
        'compute-1-26' ...
        'compute-1-27' ...
        'compute-1-28' ...
        };
    %'compute-1-23' ...
    eval( MPI_Run('LHDMPrimGeneratorMPI',  216, machines) );

else
    fprintf('system not recognized\n');
end



