gen:
	octave --no-history --silent traj_01_straight.m
	octave --no-history --silent traj_02_curve.m
	octave --no-history --silent traj_03_fakeeight.m

clean:
	rm -f *.txt


# dummy targets
.PHONY: clean
