#set a task to the vehicle execution node TODO a map of whatever kind should also be provided here
orunav_msgs/RobotTarget target
bool start_from_current_state
orunav_msgs/Shape[] extra_obstacles
---
int32 RESULT_OK = 0
int32 RESULT_PATH_PLANNER_SERVICE_FAILED = 1
int32 RESULT_PATH_PLANNER_FAILED = 2
int32 RESULT_PATH_PLANNER_REPOSITIONING_FAILED = 3
int32 RESULT_POLYGONCONSTRAINT_SERVICE_FAILED = 4
int32 RESULT_SMOOTHING_SERVICE_FAILED = 5
int32 RESULT_SMOOTHING_FAILED = 6

int32 result
orunav_msgs/Task task
