<?xml version="1.0"?>

<robot name="btruck" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Prefix for includes etc. -->
  <xacro:arg name="tf_prefix" default=""/>

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find cititruck_description)/urdf/bt_truck.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find cititruck_description)/urdf/materials.xacro" />
  <!-- Adds extra joints for calibration of sensors -->
  <xacro:include filename="$(find cititruck_description)/urdf/sensor_calibration_assembly.xacro" />

  <xacro:property name="forks_pidP" value="2000" />
  <xacro:property name="forks_pidI" value="0" />
  <xacro:property name="forks_pidD" value="10" />
  
  <xacro:property name="forks_low" value="0.08" />    
  <xacro:property name="forks_high" value="1" />
  
  <xacro:property name="forks_maxeffort" value="1000" />
  
  <!-- Constants -->
  <xacro:property name="M_PI" value="3.1415927" />


 <!-- BTruck dimension paraemters -->

    <xacro:property name="x" value="0.786" />
    <xacro:property name="y" value="1.604" />
    <xacro:property name="m1" value="0.055" />
    <xacro:property name="b1" value="0.79" />
    <xacro:property name="l2" value="1.186" />
    <xacro:property name="h3" value="1.712" />
    <xacro:property name="b11" value="0.38" />
    <xacro:property name="h13" value="0.091" />
    <xacro:property name="e" value="0.18" />
    <xacro:property name="l" value="1.2" />
    <xacro:property name="x_pilar" value="0.24" />
    <xacro:property name="y_pilar" value="0.05" /> <!-- to check -->
    <xacro:property name="z_pilar" value="2.25" />
    <xacro:property name="y_sensor_platform" value="0.64" /> <!--external distance between pilars-->
    <xacro:property name="b5" value="0.55" />
    <xacro:property name="z_sensor_bar" value="0.04" />
    <xacro:property name="rear_wheel_diameter" value="0.085" /> 
    <xacro:property name="rear_wheel_length" value="0.075" />
    <xacro:property name="front_wheel_length" value="0.05" />
    <xacro:property name="front_wheel_diameter" value="0.150" />
    <xacro:property name="x_sick" value="0.1" />
    <xacro:property name="y_sick" value="0.1" />
    <xacro:property name="z_sick" value="0.1" />

  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack dedpends on this frame and KDL needs a root link without any inteltia -->
    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${m1}" rpy="0 0 0" />
      <child link="base_link" />
      <parent link="base_footprint"/>
    </joint>

  <!-- Base Link -->
  <link name="base_link">
    <inertial>
      <mass value="20"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      <origin/>
    </inertial>
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://cititruck_description/meshes/forklift_body.stl" scale="0.001 0.001 0.001"/>
          </geometry>
	  <material name="white"/>
        </visual> 
    <collision>
      <origin xyz="${(y - x - x_pilar)/2.0 + x + x_pilar} 0 0.1" rpy="0 0 0" />
      <geometry>
        <box size="${y - x - x_pilar} ${b1} 0.005" />
      </geometry>
    </collision>
  </link>

<!-- Forlift Forks -->


    <link name="base_fork">
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                 iyy="0.01" iyz="0.0" izz="0.01" />
      </inertial>
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://cititruck_description/meshes/forklift_forks.stl" scale="0.001 0.001 0.001"/>
          </geometry>
	  <material name="green"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="${l} ${b5} ${h13}" />
        </geometry>
    <contact_coefficients mu="1" kp="10.0" kd="10.0"/>
      </collision>
    </link>

   
<!-- lift speed with load 0.07 (m/s) not applied  -->
    <joint name="fork_joint" type="prismatic">
      <origin xyz="${x - l/2.0} 0.0 0.0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_fork"/>
      <axis xyz="0 0 1" />
      <limit lower="0" upper="${h3}" effort="1000" velocity="100" /> 
    </joint>




    
<!-- Rear Steering Wheel -->
    <link name="steer_link">
        <inertial>
          <mass value="0.01"/>
          <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.03 0.03 0.03" />
          </geometry>
          <material name="orange"/>
        </visual>
      </link>
      
      <link name="sd_wheel_link">
        <inertial>
          <mass value="10"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_length}" />
          </geometry>
          <material name="black"/>
        </visual>
        
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_length}" />
          </geometry>
        </collision>
      </link>

      <joint name="base2steer_joint" type="revolute">
        <parent link="base_link"/>
        <child link="steer_link"/>
        <limit effort="10000.0" lower="-1.57" upper="1.57" velocity="100"/>
        <origin xyz="${y} 0 ${rear_wheel_diameter/2 - m1}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
      </joint>

      <joint name="steer2sd_wheel_joint" type="continuous">
        <parent link="steer_link"/>
        <child link="sd_wheel_link"/>
        <limit effort="10000.0" velocity="100"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
      </joint>

<!-- Front Wheels -->

      <link name="fixed_left_wheel_link">
        <inertial>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder radius="${front_wheel_diameter/2.0}" length="${front_wheel_length}" />
          </geometry>
          <material name="gray"/>
        </visual>
        
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder radius="${front_wheel_diameter/2.0}" length="${front_wheel_length}" />
          </geometry>
         <!-- <contact_coefficients mu="100" kp="10.0" kd="0.1"/> -->
        </collision>
      </link>
      
      <joint name="base2fixed_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="fixed_left_wheel_link"/>
        <origin xyz="0 ${b5/2 - e/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
      </joint>
      
      <link name="fixed_right_wheel_link">
        <inertial>
          <mass value="0.1"/>
          <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
          <origin/>
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder radius="${front_wheel_diameter/2.0}" length="${front_wheel_length}" />
          </geometry>
          <material name="gray"/>
        </visual>
        
        <collision>
          <origin xyz="0 0 0" rpy="1.57 0 0" />
          <geometry>
            <cylinder radius="${front_wheel_diameter/2.0}" length="${front_wheel_length}" />
          </geometry>
         <!-- <contact_coefficients mu="100" kp="10.0" kd="0.1"/> -->
        </collision>
      </link>

      <joint name="base2fixed_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="fixed_right_wheel_link"/>
        <origin xyz="0 ${-(b5/2 - e/2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
      </joint>



<!-- ***********************************************
     ********************Sensors********************
     ***********************************************  -->


<!-- Sick laser -->
      
      <link name="laser2d_floor_base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${x_sick} ${y_sick} ${z_sick}"/>
      </geometry>
    </collision>
    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
            <mesh filename="package://cititruck_description/meshes/sick_s300_laser.dae"/>
      </geometry>
    </visual>
    
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
      </link>

      <joint name="laser2d_floor_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${l2 + x -y_sick/2.0} 0 ${z_sick/2.0}" rpy="3.14159 0 0"/>
    <parent link="base_link"/>
    <child link="laser2d_floor_base_link"/>
      </joint> 

      <sensor_calibration_assembly sensor_id="laser2d_floor" parent_link="laser2d_floor_base_link"/>



<!-- Kinect V2 -->
      
    <joint name="kinect2_joint" type="fixed">
      <origin xyz="${ 0.3 + x } ${0.29 - y_sensor_platform/2.0} ${b1 + 0.76 + z_sensor_bar + 0.05}" rpy="0 0 ${M_PI}" /> <!-- check sensor height z -->
      <parent link="base_link"/>
      <child link="kinect2_base_link"/>
    </joint>

    <link name="kinect2_base_link">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://cititruck_description/meshes/kinect_v2.dae"/>
          </geometry>
          </visual>
    </link>

    <sensor_calibration_assembly sensor_id="kinect2" parent_link="kinect2_base_link" final_link_suffix="before_optical_link"/>

    <!-- Extra joint added to get pointcloud aligned correctly in bagfiles; do not remove without cross-checking against recorded bagfiles -->
    <!-- TODO: Check against live data on robot when running kinect2_bridge -->
    <joint name="kinect2_optical_joint" type="fixed">
      <origin rpy="${-M_PI/2.0} 0 ${-M_PI/2.0}"/>
      <parent link="kinect2_before_optical_link"/>
      <child link="kinect2_link"/>
    </joint>
    <link name="kinect2_link"/>

<!-- Velodyne HDL32E -->


    <joint name="velodyne_base_joint" type="fixed">
      <origin xyz="1.10127 -0.1121022 1.75" rpy="0.00234404 -0.00292631 1.49467"/> 
      <parent link="base_link"/>
      <child link="velodyne_link"/>
    </joint>

    <link name="velodyne_link">
      <inertial>
        <mass value="0.01"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.09081" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://cititruck_description/meshes/HDL32E_scan.dae" />
        </geometry>
      </visual>
    </link>


    <joint name="velodyne_mount_joint" type="fixed" >
      <origin xyz="0 0 -0.09081" rpy="0 0 0" />
      <parent link="velodyne_link" />
      <child link="velodyne_mount_link"/>
    </joint>

    <link name="velodyne_mount_link">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0.07212"/>
        <inertia ixx="${(1.0 * (3.0*0.04267*0.04267 + 0.14424*0.14424)) / 12.0}" ixy="0" ixz="0"
          iyy="${(1.0 * (3.0*0.04267*0.04267 + 0.14424*0.14424)) / 12.0}" iyz="0"
          izz="${0.5 * 1.0 * (0.04267*0.04267)}"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://cititruck_description/meshes/HDL32E_base.dae" />
        </geometry>
      </visual>
      <!--
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0.07212"/>
        <geometry>
          <cylinder radius="0.04267" length="0.14424"/>
        </geometry>
      </collision>
  -->
    </link>






    

<!-- Asus camera Up -->
    <joint name="asus_side_joint" type="fixed">
        <origin xyz="${x + x_pilar/2.0} ${y_sensor_platform/2.0 + .06} ${b1 + .6 + z_sensor_bar}" rpy="0 0 ${M_PI/2}"/> 
        <parent link="base_link"/>
        <child link="asus_side_base_link"/>
      </joint>
      
      <link name="asus_side_base_link"/>
      
      <sensor_calibration_assembly sensor_id="asus_side" parent_link="asus_side_base_link" create_final_link="false"/>

      <link name="asus_side_link">
        <inertial>
          <mass value="0.200" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://cititruck_description/meshes/asus_camera_simple.dae"/>
          </geometry>
        </visual>
        
            <!--
          <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.035 0.185 0.025"/>
        </geometry>
          </collision>
        -->
    </link>





  
<!-- Intel Realsense camera on fork -->
    <!-- FIXME: origin -->
    <joint name="realsense_fork_joint" type="fixed">
        <origin xyz="${l/2} 0 0.235" rpy="0 0 ${M_PI}"/> 
        <parent link="base_fork"/>
        <child link="realsense_fork_base_link"/>
      </joint>
      
      <link name="realsense_fork_base_link"/>


      <sensor_calibration_assembly sensor_id="realsense_fork" parent_link="realsense_fork_base_link" create_final_link="false"/>

    <link name="realsense_fork_link">
        <inertial>
          <mass value="0.200" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://cititruck_description/meshes/asus_camera_simple.dae"/>
          </geometry>
        </visual>
        
        <!--
      <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <box size="0.035 0.185 0.025"/>
    </geometry>
      </collision>  -->
      </link>






<!-- Reflex camera -->
    <!-- FIXME: origin -->
      <joint name="reflex_joint" type="fixed">
        <origin xyz="${x + x_pilar/2.0} .09 1.90" rpy="0 0 ${M_PI}"/> 
        <parent link="base_link"/>
        <child link="reflex_base_link"/>
      </joint>
      
      <link name="reflex_base_link"/>

      <sensor_calibration_assembly sensor_id="reflex" parent_link="reflex_base_link" create_final_link="false"/>

      <link name="reflex_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="0.11 0.35 0.07"/>
                </geometry>
            <material name="black"/>
        </visual>
        <!--
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.035 0.185 0.025"/>
          </geometry>
        </collision>
    -->
      </link>

<!-- LS2000 -->

      <link name="laser2d_top_base_link">
        <inertial>
          <mass value="0.200" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <inertia ixx="5.8083e-4" ixy="0" ixz="0" iyy="3.0833e-5" iyz="0" izz="5.9083e-4" />
        </inertial>
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://cititruck_description/meshes/ls2000_laser.dae"/>
          </geometry>
        </visual>       
            <!--
          <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.035 0.185 0.025"/>
        </geometry>
          </collision>
        -->
    </link>

      <joint name="laser2d_top_base_joint" type="fixed">
        <origin xyz="1.257 0 2.3005" rpy="0 0 ${M_PI}"/> 
        <parent link="base_link"/>
        <child link="laser2d_top_base_link"/>
      </joint>

      <sensor_calibration_assembly sensor_id="laser2d_top" parent_link="laser2d_top_base_link"/>


</robot>
