all:
#	maple get_abc.mpl > out.txt
	gcc -O3 -c get_abc.c

#	maple get_parameters_xy.mpl > out.txt
	gcc -O3 -c get_parameters_xy.c

#	maple poly3_coefficients.mpl > out.txt
#	gcc -O3 -c poly3_coefficients.c

#	maple poly1_coefficients.mpl > out.txt
#	gcc -O3 -c poly1_coefficients.c

clean:
	rm -f *.o
	rm -f out.txt

# dummy targets
.PHONY: clean
